concurrent = 16
log_level = "info"

[session_server]
  session_timeout = 1800

[[runners]]
  name = "manytask-private-heavy-0"
  limit = 4
  url = "https://gitlab.com/"
  token = "TOKEN"
  executor = "docker"
  environment = ["DOCKER_HOST=unix:///var/run/docker.sock", "DOCKER_TLS_CERTDIR=\"\""]
  [runners.docker]
    tls_verify = false
    tls_certs_path = ""
    image = "docker:stable"
    privileged = true
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache", "/var/run/docker.sock:/var/run/docker.sock"]
    pull_policy = ["always"]
    shm_size = 0

[[runners]]
  name = "manytask-public-heavy-0"
  limit = 16
  url = "https://gitlab.manytask.org/"
  token = "TOKEN"
  executor = "docker"
  pre_build_script = "cmp $CI_CONFIG_PATH /opt/shad/.grader-ci.yml # echo 'If this fails you need to pull latest changes'"
  [runners.docker]
    tls_verify = false
    image = "docker:latest"
    memory = "512m"
    cpus = "4"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    allowed_images = ["cr.yandex/crp9onavos88ug32d5r2/grader/py/*"]
    pull_policy = ["always"]
    shm_size = 0
